sudo: required
dist: trusty

language: haxe

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.2"

install:
  - haxelib install msignal
  - haxelib install Sure

script:
  - pushd src
  - haxe NeedsAI.hxml debug.hxml
  - haxe NeedsAI.hxml release.hxml
  - popd